const ACTION_TYPES = {
  SET_PRODUCT: "SET_PRODUCT",
  SET_FILTEREDATA: "SET_FILTEREDATA",
  FILTERE_DATA: "FILTERE_DATA",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_CART_FROM_SINGLE: "ADD_CART_FROM_SINGLE",
  CHANGE_QUANTITY: "CHANGE_QUANTITY",
  GET_CATEGORY_NAME: "GET_CATEGORY_NAME",
  FETCH_SINGLE_PRODUCT: "FETCH_SINGLE_PRODUCT",
};

export default ACTION_TYPES;
